apps:
  - script: "material-collector.js"
    name: "x5process_material_collect"
    cwd: "./dist/"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_material_text_indexing"
    cwd: "./dist/"
    args: "-tn uuid.index-material-text -tp ../topologies/index-material-text"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_material_text_translation"
    cwd: "./dist/"
    args: "-tn uuid.index-material-text-translate -tp ../topologies/index-material-text-translate"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_material_video_translation"
    cwd: "./dist/"
    args: "-tn uuid.index-material-video-translate -tp ../topologies/index-material-video-translate"
    instances: 3,
    exec_mode: "cluster"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_material_store_complete"
    cwd: "./dist/"
    args: "-tn uuid.index-material-store-complete -tp ../topologies/index-material-store-complete"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"


  - script: "pipeline.js"
    name: "x5process_material_store_incomplete"
    cwd: "./dist/"
    args: "-tn uuid.index-material-store-incomplete -tp ../topologies/index-material-store-incomplete"
    instances: 1,
    exec_mode: "fork"
    autorestart: true
    watch: false
    env:
      NODE_ENV: "development"
    env_production:
      NODE_ENV: "production"